services:
  backend:
    build:
      context: .
      dockerfile: SharpbinV3.Server/Dockerfile
    image: sharpbin-backend
    container_name: sharpbin-backend
    env_file:
      - "backend.env"
    environment:
      DATA_PROTECTION_KEY_PATH: /app/data/keys
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/sharpbin.db"
    volumes:
      - sharpbin-data:/app/data
      - ./SharpbinV3.Server/appsettings.json:/app/appsettings.json
    networks:
      - sharpbin-net
    healthcheck:
      test: 'wget --no-verbose --spider http://localhost:8080/health || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  frontend:
    build:
      context: ./SharpbinV3.Client
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_HASH: ${GIT_COMMIT_HASH}
    image: sharpbin-frontend
    container_name: sharpbin-frontend
    env_file:
      - "frontend.env"
    environment:
      VITE_API_URL: http://backend:8080

    ports:
      - "5173:5173"
    networks:
      - sharpbin-net
    healthcheck:
      test: 'wget --no-verbose --spider http://localhost:5173/health || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  sharpbin-data:


networks:
  sharpbin-net:
    driver: bridge
