services:
  backend:
    build:
      context: .
      dockerfile: SharpbinV3.Server/Dockerfile
    image: sharpbin-backend
    container_name: sharpbin-backend
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection:-Data Source=/app/data/sharpbin.db}
      DATA_PROTECTION_KEY_PATH: ${DATA_PROTECTION_KEY_PATH:-"/app/data/keys"}
      JwtSettings__Secret: ${JwtSettings__Secret}
      AuthSettings__First_User_Admin: ${AuthSettings__First_User_Admin}
      AuthSettings__CF_Turnstile_SecretKey: ${AuthSettings__CF_Turnstile_SecretKey}
      AuthSettings_CF_Turnstile_SiteKey: ${AuthSettings_CF_Turnstile_SiteKey}

    volumes:
      - sharpbin-data:/app/data
      - ./SharpbinV3.Server/appsettings.json:/app/appsettings.json
    networks:
      - sharpbin-net
    healthcheck:
      test: 'wget --no-verbose --spider http://localhost:8080/health || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  frontend:
    build:
      context: ./SharpbinV3.Client
      dockerfile: Dockerfile
    image: sharpbin-frontend
    container_name: sharpbin-frontend
    environment:
      VITE_API_URL: http://backend:8080
      VITE_ALLOWED_HOSTS: ${VITE_ALLOWED_HOSTS:-"localhost"}
    ports:
      - "5173:5173"
    networks:
      - sharpbin-net
    healthcheck:
      test: 'wget --no-verbose --spider http://localhost:5173/health || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  sharpbin-data:


networks:
  sharpbin-net:
    driver: bridge