export type Syntax = {
	name: string;
	extension: string;
};

export const syntaxes: Record<string, Syntax> = {
	plaintext: { name: 'Plain Text', extension: 'txt' },
	'1c': { name: '1c', extension: '' },
	abnf: { name: 'Augmented Backus-Naur Form', extension: 'abnf' },
	accesslog: { name: 'Access Log', extension: 'log' },
	actionscript: { name: 'ActionScript', extension: 'as' },
	ada: { name: 'Ada', extension: 'ada' },
	angelscript: { name: 'AngelScript', extension: 'angelscript' },
	apache: { name: 'Apache', extension: 'apache' },
	applescript: { name: 'AppleScript', extension: 'applescript' },
	arcade: { name: 'Arcade', extension: 'arcade' },
	arduino: { name: 'Arduino', extension: 'ino' },
	arm: { name: 'ARM Assembly', extension: 's' },
	asciidoc: { name: 'AsciiDoc', extension: 'adoc' },
	aspectj: { name: 'AspectJ', extension: 'aj' },
	autohotkey: { name: 'AutoHotkey', extension: 'ahk' },
	autoit: { name: 'AutoIt', extension: 'au3' },
	avrasm: { name: 'AVR Assembly', extension: 's' },
	awk: { name: 'AWK', extension: 'awk' },
	bash: { name: 'Bash', extension: 'sh' },
	basic: { name: 'BASIC', extension: 'bas' },
	bnf: { name: 'Backus-Naur Form', extension: 'bnf' },
	brainfuck: { name: 'Brainfuck', extension: 'bf' },
	c: { name: 'C', extension: 'c' },
	cpp: { name: 'C++', extension: 'cpp' },
	hpp: { name: 'C++ Header', extension: 'h' },
	csharp: { name: 'C#', extension: 'cs' },
	cal: { name: 'C/AL', extension: '' },
	cos: { name: 'Cache Object Script', extension: '' },
	capnproto: { name: "Cap'n Proto", extension: 'capnp' },
	clojure: { name: 'Clojure', extension: 'clj' },
	cmake: { name: 'CMake', extension: 'cmake' },
	coffeescript: { name: 'CoffeeScript', extension: 'coffee' },
	coq: { name: 'Coq', extension: 'v' },
	crmsh: { name: 'CRMsH', extension: '' },
	crystal: { name: 'Crystal', extension: 'cr' },
	csp: { name: 'CSP', extension: 'csp' },
	css: { name: 'CSS', extension: 'css' },
	csv: { name: 'CSV', extension: 'csv' },
	d: { name: 'D', extension: 'd' },
	dart: { name: 'Dart', extension: 'dart' },
	deplhi: { name: 'Delphi', extension: 'pas' },
	diff: { name: 'Diff', extension: 'diff' },
	django: { name: 'Django', extension: 'django' },
	dns: { name: 'DNS Zone', extension: 'dns' },
	dockerfile: { name: 'Dockerfile', extension: 'dockerfile' },
	dos: { name: 'DOS', extension: 'bat' },
	bat: { name: 'Batchfile', extension: 'bat' },
	dsconfig: { name: 'DSConfig', extension: '' },
	dts: { name: 'Device Tree', extension: 'dts' },
	dust: { name: 'Dust', extension: 'dust' },
	ebnf: { name: 'Extended Backus-Naur Form', extension: 'ebnf' },
	elixir: { name: 'Elixir', extension: 'ex' },
	elm: { name: 'Elm', extension: 'elm' },
	erlang: { name: 'Erlang', extension: 'erl' },
	excel: { name: 'Excel', extension: 'xlsx' },
	fsharp: { name: 'F#', extension: 'fs' },
	fix: { name: 'FIX', extension: 'fix' },
	flix: { name: 'Flix', extension: 'flix' },
	fortran: { name: 'Fortran', extension: 'f90' },
	gcode: { name: 'G-code', extension: 'gcode' },
	gams: { name: 'GAMS', extension: 'gms' },
	gauss: { name: 'GAUSS', extension: 'gss' },
	gherkin: { name: 'Gherkin', extension: '' },
	go: { name: 'Go', extension: 'go' },
	golo: { name: 'Golo', extension: 'golo' },
	gradle: { name: 'Gradle', extension: 'gradle' },
	graphql: { name: 'GraphQL', extension: 'graphql' },
	groovy: { name: 'Groovy', extension: 'groovy' },
	haml: { name: 'HAML', extension: 'haml' },
	handlebars: { name: 'Handlebars', extension: 'hbs' },
	haskell: { name: 'Haskell', extension: 'hs' },
	haxe: { name: 'Haxe', extension: 'hx' },
	html: { name: 'HTML', extension: 'html' },
	xml: { name: 'XML', extension: 'xml' },
	rss: { name: 'RSS', extension: 'rss' },
	atom: { name: 'Atom', extension: 'atom' },
	svg: { name: 'SVG', extension: 'svg' },
	http: { name: 'HTTP', extension: 'http' },
	https: { name: 'HTTPS', extension: 'http' },
	hy: { name: 'Hy', extension: 'hy' },
	inform7: { name: 'Inform 7', extension: 'ni' },
	ini: { name: 'INI', extension: 'ini' },
	toml: { name: 'TOML', extension: 'toml' },
	irpf90: { name: 'IRPF90', extension: 'irpf90' },
	java: { name: 'Java', extension: 'java' },
	javascript: { name: 'JavaScript', extension: 'js' },
	jolie: { name: 'Jolie', extension: 'ol' },
	json: { name: 'JSON', extension: 'json' },
	json5: { name: 'JSON5', extension: 'json5' },
	julia: { name: 'Julia', extension: 'jl' },
	'julia-repl': { name: 'Julia REPL', extension: '' },
	kotlin: { name: 'Kotlin', extension: 'kt' },
	lasso: { name: 'Lasso', extension: 'lasso' },
	latex: { name: 'LaTeX', extension: 'tex' },
	ldif: { name: 'LDIF', extension: 'ldif' },
	leaf: { name: 'Leaf', extension: 'leaf' },
	less: { name: 'Less', extension: 'less' },
	lisp: { name: 'Lisp', extension: 'lisp' },
	livecodeserver: { name: 'LiveCode Server', extension: '' },
	livescript: { name: 'LiveScript', extension: 'ls' },
	lua: { name: 'Lua', extension: 'lua' },
	makefile: { name: 'Makefile', extension: 'makefile' },
	markdown: { name: 'Markdown', extension: 'md' },
	mathematica: { name: 'Mathematica', extension: 'nb' },
	matlab: { name: 'MATLAB', extension: 'm' },
	maxima: { name: 'Maxima', extension: 'max' },
	mel: { name: 'Maya Embedded Language', extension: 'mel' },
	mercury: { name: 'Mercury', extension: 'm' },
	mipsasm: { name: 'MIPS Assembly', extension: 's' },
	mizar: { name: 'Mizar', extension: 'miz' },
	mojolicious: { name: 'Mojolicious', extension: '' },
	monkey: { name: 'Monkey', extension: 'monkey' },
	moonscript: { name: 'MoonScript', extension: 'moon' },
	n1ql: { name: 'N1QL', extension: '' },
	nginx: { name: 'Nginx', extension: 'nginx' },
	nim: { name: 'Nim', extension: 'nim' },
	nix: { name: 'Nix', extension: 'nix' },
	nsis: { name: 'NSIS', extension: 'nsi' },
	objectivec: { name: 'Objective-C', extension: 'm' },
	ocaml: { name: 'OCaml', extension: 'ml' },
	glsl: { name: 'OpenGL Shading Language', extension: 'glsl' },
	openscad: { name: 'OpenSCAD', extension: 'scad' },
	ruleslanguage: { name: 'Oracle Rules Language', extension: '' },
	oxygene: { name: 'Oxygene', extension: 'oxygene' },
	parser3: { name: 'Parser3', extension: '' },
	perl: { name: 'Perl', extension: 'pl' },
	pf: { name: 'PF', extension: 'pf' },
	php: { name: 'PHP', extension: 'php' },
	pony: { name: 'Pony', extension: 'pony' },
	postgresql: { name: 'PostgreSQL', extension: 'sql' },
	powershell: { name: 'PowerShell', extension: 'ps1' },
	processing: { name: 'Processing', extension: 'pde' },
	prolog: { name: 'Prolog', extension: 'pl' },
	properties: { name: 'Java Properties', extension: 'properties' },
	protobuf: { name: 'Protocol Buffers', extension: 'proto' },
	puppet: { name: 'Puppet', extension: 'pp' },
	python: { name: 'Python', extension: 'py' },
	profiler: { name: 'Poython Profiler Results', extension: '' },
	'python-repl': { name: 'Python REPL', extension: '' },
	q: { name: 'Q', extension: 'q' },
	qml: { name: 'QML', extension: 'qml' },
	r: { name: 'R', extension: 'r' },
	reasonml: { name: 'ReasonML', extension: 're' },
	rib: { name: 'RenderMan Interface Bytestream', extension: 'rib' },
	rsl: { name: 'RenderMan Shading Language', extension: 'rsl' },
	graph: { name: 'Roboconf', extension: '' },
	ruby: { name: 'Ruby', extension: 'rb' },
	rust: { name: 'Rust', extension: 'rs' },
	sas: { name: 'SAS', extension: 'sas' },
	scala: { name: 'Scala', extension: 'scala' },
	scheme: { name: 'Scheme', extension: 'scm' },
	scilab: { name: 'Scilab', extension: 'sci' },
	scss: { name: 'SCSS', extension: 'scss' },
	shell: { name: 'Shell', extension: 'sh' },
	smali: { name: 'Smali', extension: 'smali' },
	smalltalk: { name: 'Smalltalk', extension: 'st' },
	sml: { name: 'Standard ML', extension: 'sml' },
	sql: { name: 'SQL', extension: 'sql' },
	stan: { name: 'Stan', extension: 'stan' },
	stata: { name: 'Stata', extension: 'do' },
	step21: { name: 'STEP Part 21', extension: 'stp' },
	stylus: { name: 'Stylus', extension: 'styl' },
	subunit: { name: 'SubUnit', extension: 'subunit' },
	svelte: { name: 'Svelte', extension: 'svelte' }, // svelte seems to work even though the docs say it requires a plugin
	swift: { name: 'Swift', extension: 'swift' },
	tcl: { name: 'Tcl', extension: 'tcl' },
	tap: { name: 'Test Anything Protocol', extension: 'tap' },
	thrift: { name: 'Thrift', extension: 'thrift' },
	toit: { name: 'Toit', extension: 'toit' },
	tp: { name: 'TP', extension: 'tp' },
	twig: { name: 'Twig', extension: 'twig' },
	typescript: { name: 'TypeScript', extension: 'ts' },
	vala: { name: 'Vala', extension: 'vala' },
	vbnet: { name: 'VB.NET', extension: 'vb' },
	vba: { name: 'VBA', extension: 'vba' },
	vbscript: { name: 'VBScript', extension: 'vbs' },
	verilog: { name: 'Verilog', extension: 'v' },
	vhdl: { name: 'VHDL', extension: 'vhd' },
	vim: { name: 'Vim Script', extension: 'vim' },
	axapta: { name: 'X++', extension: 'xpp' },
	x86asm: { name: 'x86 Assembly', extension: 's' },
	xl: { name: 'XL', extension: 'xl' },
	xquery: { name: 'XQuery', extension: 'xq' },
	yaml: { name: 'YAML', extension: 'yaml' },
	zephir: { name: 'Zephir', extension: 'zep' }
};

export const expiresOptions = [
	{ value: 0, label: 'Never Expire' },
	{ value: 300000, label: 'Expire in 5 Minutes' },
	{ value: 600000, label: 'Expire in 10 Minutes' },
	{ value: 1800000, label: 'Expire in 30 Minutes' },
	{ value: 3600000, label: 'Expire in 1 Hour' },
	{ value: 21600000, label: 'Expire in 6 Hours' },
	{ value: 43200000, label: 'Expire in 12 Hours' },
	{ value: 86400000, label: 'Expire in 1 Day' },
	{ value: 604800000, label: 'Expire in 1 Week' },
	{ value: 1209600000, label: 'Expire in 2 Weeks' },
	{ value: 2592000000, label: 'Expire in 1 Month' },
	{ value: 7776000000, label: 'Expire in 3 Months' },
	{ value: 15552000000, label: 'Expire in 6 Months' },
	{ value: 31536000000, label: 'Expire in 1 Year' },
	{ value: 63072000000, label: 'Expire in 2 Years' },
	{ value: 157680000000, label: 'Expire in 5 Years' },
	{ value: 315360000000, label: 'Expire in 10 Years' }
];

export const trustedDomains = [
	'img.youtube.com',
	'i.ytimg.com',

	'github.com',
	'githubusercontent.com',
	'avatars.githubusercontent.com',
	'camo.githubusercontent.com',
	'raw.githubusercontent.com',
	'github.githubassets.com',

	'cdn.discordapp.com',
	'media.discordapp.net',

	'i.redd.it',
	'v.redd.it',
	'external-preview.redd.it',
	'preview.redd.it',

	'i.imgur.com',
	'imgur.com',

	'pbs.twimg.com',
	'video.twimg.com',
	'twitter.com',
	'x.com',

	'images.cloudflare.com',
	'cloudflare-ipfs.com',

	'upload.wikimedia.org'
];