export type Syntax = {
	name: string;
	extension: string;
};

export const syntaxes: Record<string, Syntax> = {
	plaintext: { name: 'Plain Text', extension: '' },
	abap: { name: 'ABAP', extension: '.abap' },
	'actionscript-3': { name: 'ActionScript 3', extension: '.as' },
	ada: { name: 'Ada', extension: '.adb' },
	apache: { name: 'Apache', extension: '.conf' },
	apex: { name: 'Apex', extension: '.cls' },
	apl: { name: 'APL', extension: '.apl' },
	applescript: { name: 'AppleScript', extension: '.applescript' },
	ara: { name: 'ARA', extension: '.ara' },
	asm: { name: 'Assembly', extension: '.asm' },
	astro: { name: 'Astro', extension: '.astro' },
	awk: { name: 'AWK', extension: '.awk' },
	ballerina: { name: 'Ballerina', extension: '.bal' },
	bat: { name: 'Batch', extension: '.bat' },
	berry: { name: 'Berry', extension: '.be' },
	bibtex: { name: 'BibTeX', extension: '.bib' },
	bicep: { name: 'Bicep', extension: '.bicep' },
	blade: { name: 'Blade', extension: '.blade.php' },
	c: { name: 'C', extension: '.c' },
	cadence: { name: 'Cadence', extension: '.cdc' },
	clarity: { name: 'Clarity', extension: '.clar' },
	clojure: { name: 'Clojure', extension: '.clj' },
	cmake: { name: 'CMake', extension: '.cmake' },
	cobol: { name: 'COBOL', extension: '.cob' },
	codeql: { name: 'CodeQL', extension: '.ql' },
	coffee: { name: 'CoffeeScript', extension: '.coffee' },
	cpp: { name: 'C++', extension: '.cpp' },
	crystal: { name: 'Crystal', extension: '.cr' },
	csharp: { name: 'C#', extension: '.cs' },
	css: { name: 'CSS', extension: '.css' },
	cue: { name: 'CUE', extension: '.cue' },
	d: { name: 'D', extension: '.d' },
	dart: { name: 'Dart', extension: '.dart' },
	diff: { name: 'Diff', extension: '.diff' },
	docker: { name: 'Docker', extension: 'Dockerfile' },
	'dream-maker': { name: 'Dream Maker', extension: '.dm' },
	elixir: { name: 'Elixir', extension: '.ex' },
	elm: { name: 'Elm', extension: '.elm' },
	erb: { name: 'ERB', extension: '.erb' },
	erlang: { name: 'Erlang', extension: '.erl' },
	fish: { name: 'Fish', extension: '.fish' },
	fsharp: { name: 'F#', extension: '.fs' },
	gdresource: { name: 'Godot Resource', extension: '.tres' },
	gdscript: { name: 'GDScript', extension: '.gd' },
	gdshader: { name: 'Godot Shader', extension: '.gdshader' },
	gherkin: { name: 'Gherkin', extension: '.feature' },
	'git-commit': { name: 'Git Commit', extension: '' },
	'git-rebase': { name: 'Git Rebase', extension: '' },
	glsl: { name: 'GLSL', extension: '.glsl' },
	gnuplot: { name: 'Gnuplot', extension: '.gp' },
	go: { name: 'Go', extension: '.go' },
	graphql: { name: 'GraphQL', extension: '.graphql' },
	groovy: { name: 'Groovy', extension: '.groovy' },
	hack: { name: 'Hack', extension: '.hack' },
	haml: { name: 'Haml', extension: '.haml' },
	handlebars: { name: 'Handlebars', extension: '.hbs' },
	haskell: { name: 'Haskell', extension: '.hs' },
	hcl: { name: 'HCL', extension: '.hcl' },
	hjson: { name: 'HJSON', extension: '.hjson' },
	hlsl: { name: 'HLSL', extension: '.hlsl' },
	html: { name: 'HTML', extension: '.html' },
	ini: { name: 'INI', extension: '.ini' },
	java: { name: 'Java', extension: '.java' },
	javascript: { name: 'JavaScript', extension: '.js' },
	jison: { name: 'Jison', extension: '.jison' },
	json: { name: 'JSON', extension: '.json' },
	json5: { name: 'JSON5', extension: '.json5' },
	jsonc: { name: 'JSONC', extension: '.json' },
	jsonnet: { name: 'Jsonnet', extension: '.jsonnet' },
	jssm: { name: 'JSSM', extension: '.jssm' },
	jsx: { name: 'JSX', extension: '.jsx' },
	julia: { name: 'Julia', extension: '.jl' },
	kotlin: { name: 'Kotlin', extension: '.kt' },
	latex: { name: 'LaTeX', extension: '.tex' },
	less: { name: 'Less', extension: '.less' },
	liquid: { name: 'Liquid', extension: '.liquid' },
	lisp: { name: 'Lisp', extension: '.lisp' },
	logo: { name: 'Logo', extension: '.logo' },
	lua: { name: 'Lua', extension: '.lua' },
	makefile: { name: 'Makefile', extension: '.makefile' },
	markdown: { name: 'Markdown', extension: '.md' },
	marko: { name: 'Marko', extension: '.marko' },
	matlab: { name: 'MATLAB', extension: '.m' },
	mdx: { name: 'MDX', extension: '.mdx' },
	nginx: { name: 'Nginx', extension: '.conf' },
	nim: { name: 'Nim', extension: '.nim' },
	nix: { name: 'Nix', extension: '.nix' },
	'objective-c': { name: 'Objective-C', extension: '.m' },
	'objective-cpp': { name: 'Objective-C++', extension: '.mm' },
	ocaml: { name: 'OCaml', extension: '.ml' },
	pascal: { name: 'Pascal', extension: '.pas' },
	perl: { name: 'Perl', extension: '.pl' },
	php: { name: 'PHP', extension: '.php' },
	plsql: { name: 'PL/SQL', extension: '.sql' },
	postcss: { name: 'PostCSS', extension: '.pcss' },
	powerquery: { name: 'Power Query', extension: '.pq' },
	powershell: { name: 'PowerShell', extension: '.ps1' },
	prisma: { name: 'Prisma', extension: '.prisma' },
	prolog: { name: 'Prolog', extension: '.pl' },
	proto: { name: 'Protocol Buffers', extension: '.proto' },
	pug: { name: 'Pug', extension: '.pug' },
	puppet: { name: 'Puppet', extension: '.pp' },
	purescript: { name: 'PureScript', extension: '.purs' },
	python: { name: 'Python', extension: '.py' },
	r: { name: 'R', extension: '.r' },
	raku: { name: 'Raku', extension: '.raku' },
	razor: { name: 'Razor', extension: '.cshtml' },
	reg: { name: 'Registry', extension: '.reg' },
	rel: { name: 'Rel', extension: '.rel' },
	riscv: { name: 'RISC-V', extension: '.s' },
	rst: { name: 'reStructuredText', extension: '.rst' },
	ruby: { name: 'Ruby', extension: '.rb' },
	rust: { name: 'Rust', extension: '.rs' },
	sas: { name: 'SAS', extension: '.sas' },
	sass: { name: 'Sass', extension: '.sass' },
	scala: { name: 'Scala', extension: '.scala' },
	scheme: { name: 'Scheme', extension: '.scm' },
	scss: { name: 'SCSS', extension: '.scss' },
	shaderlab: { name: 'ShaderLab', extension: '.shader' },
	shell: { name: 'Shell', extension: '.sh' },
	smalltalk: { name: 'Smalltalk', extension: '.st' },
	solidity: { name: 'Solidity', extension: '.sol' },
	sparql: { name: 'SPARQL', extension: '.rq' },
	sql: { name: 'SQL', extension: '.sql' },
	'ssh-config': { name: 'SSH Config', extension: '' },
	stata: { name: 'Stata', extension: '.do' },
	stylus: { name: 'Stylus', extension: '.styl' },
	svelte: { name: 'Svelte', extension: '.svelte' },
	swift: { name: 'Swift', extension: '.swift' },
	'system-verilog': { name: 'SystemVerilog', extension: '.sv' },
	tasl: { name: 'TASL', extension: '.tasl' },
	tcl: { name: 'Tcl', extension: '.tcl' },
	tex: { name: 'TeX', extension: '.tex' },
	toml: { name: 'TOML', extension: '.toml' },
	tsx: { name: 'TSX', extension: '.tsx' },
	turtle: { name: 'Turtle', extension: '.ttl' },
	twig: { name: 'Twig', extension: '.twig' },
	typescript: { name: 'TypeScript', extension: '.ts' },
	v: { name: 'V', extension: '.v' },
	vb: { name: 'VB', extension: '.vb' },
	verilog: { name: 'Verilog', extension: '.v' },
	vhdl: { name: 'VHDL', extension: '.vhdl' },
	viml: { name: 'VimL', extension: '.vim' },
	vue: { name: 'Vue', extension: '.vue' },
	wasm: { name: 'WebAssembly', extension: '.wasm' },
	wenyan: { name: 'Wenyan', extension: '.wy' },
	xml: { name: 'XML', extension: '.xml' },
	xsl: { name: 'XSL', extension: '.xsl' },
	yaml: { name: 'YAML', extension: '.yaml' },
	zenscript: { name: 'ZenScript', extension: '.zs' }
};

export const roles = {
	0: 'User',
	1: 'Moderator',
	255: 'Administrator',
	403: 'Banned'
};

export const trustedDomains =
	[
		'img.youtube.com',
		'i.ytimg.com',

		'github.com',
		'githubusercontent.com',
		'avatars.githubusercontent.com',
		'camo.githubusercontent.com',
		'raw.githubusercontent.com',
		'github.githubassets.com',

		'cdn.discordapp.com',
		'media.discordapp.net',

		'i.redd.it',
		'v.redd.it',
		'external-preview.redd.it',
		'preview.redd.it',

		'i.imgur.com',
		'imgur.com',

		'pbs.twimg.com',
		'video.twimg.com',
		'twitter.com',
		'x.com',

		'images.cloudflare.com',
		'cloudflare-ipfs.com',

		'upload.wikimedia.org'
	];
