// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpbinV3.Server.Data;

#nullable disable

namespace SharpbinV3.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106211303_NullableAuthorUUID")]
    partial class NullableAuthorUUID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SharpbinV3.Server.Data.Entities.Paste", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AuthorUUID")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("EditedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompressed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Syntax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrueSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("PID");

                    b.HasIndex("AuthorUUID");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("PID")
                        .IsUnique();

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("Views");

                    b.HasIndex("Visibility");

                    b.ToTable("Pastes");
                });

            modelBuilder.Entity("SharpbinV3.Server.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("UserUUID")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserUUID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SharpbinV3.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastLogin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("UUID");

                    b.HasIndex("UID");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharpbinV3.Server.Data.Entities.Paste", b =>
                {
                    b.HasOne("SharpbinV3.Server.Data.Entities.User", "User")
                        .WithMany("Pastes")
                        .HasForeignKey("AuthorUUID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharpbinV3.Server.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("SharpbinV3.Server.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharpbinV3.Server.Data.Entities.User", b =>
                {
                    b.Navigation("Pastes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
